apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - route.yaml
commonLabels:
  app: codemotion-frontend
  app.kubernetes.io/instance: codemotion-frontend
  app.kubernetes.io/name: codemotion-frontend
