apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "codemotion-chart.appname" .}}-vsvc
spec:
  hosts:
  - "*"
  gateways:
  - {{ include "codemotion-chart.appname" .}}-gw
  http:
  {{- if eq .Values.deploymentType "canary" }}
  - match:
    - headers:
        deployment:
          exact: canary
    route:
    - destination:
        host: codemotion-frontend-canary
        port:
          number: 80
  - route:
    - destination:
        host: codemotion-frontend
        port:
          number: 80
  {{- else}}
  - route:
    - destination:
        host: codemotion-frontend
        port:
          number: 80
{{- end }}