apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "codemotion-chart.appname" .}}-vsvc
spec:
  hosts:
  - "*"
  gateways:
  - gw
  http:
  {{- if eq .Values.deployment.deploymentType "headerBased" }}
  - match:
    - headers:
        branch:
          exact: {{ .Values.deployment.branch }}
    route:
    - destination:
        host: codemotion-frontend-{{ .Values.deployment.branch }}
        port:
          number: 80
  {{- else if eq .Values.deployment.deploymentType "canary" }}
  - route:
    - destination:
        host: codemotion-frontend
        port:
          number: 80
  {{- else if eq .Values.deployment.deploymentType "rolling" }}
  - route:
    - destination:
        host: codemotion-frontend
        port:
          number: 80
{{- end }}