import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Codemotion Frontend Example App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/https://www.ibm.com/favicon.ico" />
      </Head>
      <header className={styles.headerSup}>
        Codemotion Demo
        </header>
        <header className={styles.header}>
        RedHat OpenShift: CI/CD pipelines into the Service Mesh
        </header>
      <main className={styles.main}>

        <h1 className={styles.title}>
        <span aria-label="Hand wave" role="img">
                  👋{' '}
                </span>{' '}
                           Welcome!                 
            <span aria-label="Hand wave" role="img">
                  👋{' '}
                </span>{' '}
        </h1>

        <p className={styles.description}>
          Tech Stack
        </p>

        <div className={styles.grid}>
          <a href="https://docs.openshift.com/container-platform/4.6/welcome/index.html" className={styles.card}>
            <h2>RedHat OpenShift</h2>
          </a>

          <a href="https://tekton.dev/" className={styles.card}>
            <h2>Tekton</h2>
          </a>
          <a href="https://istio.io/" className={styles.card}>
            <h2>Istio</h2>
          </a>
          <a
            href="https://helm.sh/" className={styles.card}>
            <h2>Helm</h2>
          </a>
        </div>
      </main>
    </div>
  )
}
